### ISSUE TITLE
Getting Project Dependencies Setup

### ISSUE THREAD

**Issue by austinbrown34** [RomainQuidet/OSRM-iOS#1]
Thanks for taking the time to put together this repo.  I've been working to get all the dependencies sorted out to be able to successfully build the ORSM target.  I think I'm close to working out the issues, but would appreciate some clarification on a few bits.

Inside the 3rdParty directory I first run ./buildAll.sh.  This gave me an error that tbb_libs directory did not exists.  I created this folder inside 3rdParty, reran the buildAll script, and libtbbUnivesal.a, as well as libtbbmallocUnivesal.a, has been generated for me.  So far so good.

I noticed that there are two separate cmake instructions that are commented out for stxxl. Is this because only one of these two cmake commands should be run depending on whether I am building for the simulator or release?

I also added this to the script:
 ```startSection "Building stxxl static lib"
cd "../stxxl"
make target="ios" arch="arm64" extra_inc="big_iron.inc"
make target="ios" arch="armv7" extra_inc="big_iron.inc"
make target="ios" arch="intel64" extra_inc="big_iron.inc"

pattern="_release"
xcrun --sdk iphoneos lipo -create build/*"${pattern}"/libstxxl.a -output ../stxxl_lib/libstxxlUniversal.a
endSection
cmake -DCMAKE_TOOLCHAIN_FILE=../iOS.cmake -DCMAKE_BUILD_TYPE=Release ../stxxl -DIOS_PLATFORM=SIMULATOR64
make stxxl
```

Before I go any further, can you confirm that these are the right and necessary steps to get this project to build?

**Comment by RomainQuidet** [comment]
Hi,

Thanks for your interest in this project, I build it for study purposes, and as you can see the dependencies build is not yet fully available.
For the moment I build the dependencies manually, I don't master cmake for iOS yet. And the 3rd party libs are not delivered to be compiled on iOS so It's all manual trick.
The aim is to build static frameworks (or static lib) for 

- boost 
- stxxl
- tbb

Protozero uses only the hpp files as far as I remember.

This is not maybe the best way to create this OSRM iOS framework, but finally I got it working quite well once you have all the dependencies available.

You're right about all the steps you made for tbb. I did it also manually for boost and stxx.
Feel free to make some PR if you succeed in putting all together into scripts !

Here is a small screenshot of my project with the libs
![capture d ecran 2017-07-13 a 09 02 41](https://user-images.githubusercontent.com/8179069/28154429-5610e180-67aa-11e7-9194-664f13ceb93e.png)

**Comment by RomainQuidet** [comment]
I also remember that I needed to check the mandatory boost sub parts, I embedded too many of them. 
And for the commented out lines for stxxl, I had some issues building device/simulator slices all together so I used the script to build manually one by one and merged all manually.

**Comment by austinbrown34** [comment]
Thank you for getting back to me!


Couple questions for you...

Which version of Boost did you build?

I think I'm close to getting this to compile, but I'm getting an error when
it tries to link.  I've attached a screenshot below to show you what I'm
talking about.

Did you run into this issue ever?  Any ideas for me?

Thanks again!

**Comment by RomainQuidet** [comment]
The boost needed by ORSM 5.6 is 1.63.0
I don't have your screenshot, I don't think github linked the attached screenshot, you need to do it via the web view.

**Comment by austinbrown34** [comment]
<img width="1394" alt="screen shot 2017-07-13 at 1 22 23 am" src="https://user-images.githubusercontent.com/4065492/28155742-32d7548e-676d-11e7-98d6-c89ea635fafe.png">

**Comment by RomainQuidet** [comment]
Simulator symbols not found... you need to check if your boost.framework contains the simulator slices.
I can't remember if the Apple-Boost-BuildScript build both device and simulator slices or if I did merge manually.

**Comment by RomainQuidet** [comment]
Ha I remember I had to modify boost.sh in the Apple-Boost-BuildScript for the mandatory sub projects:
BOOST_LIBS="atomic chrono date_time exception filesystem program_options random signals system thread test iostreams"

**Comment by austinbrown34** [comment]
Ooh cool, I'll try this and see if it fixes it!  I had already checked the archs for boost.framework and it said x86_64 was included, but maybe this is what's needed.  I'll let you know!

**Comment by austinbrown34** [comment]
Sure enough that did it!  Thank you for all your help!  I'll make a PR once I have time to get everything in order.

**Comment by RomainQuidet** [comment]
Great !
